package com.webank.wedatasphere.dss.datamodel.center.common.service;

public interface DatamodelIndicatorReferenceService extends IndicatorDimensionReferenceService,IndicatorMeasuredReferenceService{
}
