package com.webank.wedatasphere.dss.datamodel.center.common.service;


public interface DataWarehouseIndicatorReferenceService extends IndicatorThemeReferenceService,IndicatorModifierReferenceService,IndicatorCycleReferenceService,IndicatorLayerReferenceService{
}
