export default {
  'sql': require('./images/workflow/sql.png'),
  'python': require('./images/workflow/python.png'),
  'pyspark': require('./images/workflow/pyspark.png'),
  'scala': require('./images/workflow/scala.png'),
  'hql': require('./images/workflow/hql.png'),
  'shell': require('./images/workflow/shell.png'),
  'display': require('./images/workflow/display.png'),
  'dashboard': require('./images/workflow/dashboard.png'),
  'widget': require('./images/workflow/widget.png'),
  'mlss': require('./images/workflow/mlss.png'),
  'eventreceiver': require('./images/workflow/eventreceiver.png'),
  'eventsender': require('./images/workflow/eventsender.png'),
  'datachecker': require('./images/workflow/datachecker.png'),
  'connector': require('./images/workflow/connector.png'),
  'subFlow': require('./images/workflow/subflow.png'),
  'sendemail': require('./images/workflow/sendemail.png'),
}
