name: DSS feature request
description: Suggest an idea for DSS project
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for finding the time to propose a new feature!
        We really appreciate the community efforts to improve DSS.
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) first to see
        whether the same feature was requested already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/WeBankFinTech/DataSphereStudio/issues) and found no similar
            feature requirement.
          required: true
  - type: textarea
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature

  - type: textarea
    attributes:
      label: Use case
      description: >
        Describe the use case of your feature request.
      placeholder: >
        Describe the solution you'd like A clear and concise description of what you want to happen.

  - type: textarea
    attributes:
      label: solutions
      description: Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    attributes:
      label: Anything else
      description: Anything else we need to know?
      placeholder: >
        Additional context Add any other context or screenshots about the feature request here.

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the feature.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
