eureka:
  client:
    registry-fetch-interval-seconds: 8
    serviceUrl:
      defaultZone: http://127.0.0.1:20303/eureka/
  instance:
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml

ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000

feign:
  client:
    config:
      default:
        connectTimeout: 90000
        readTimeout: 90000
