#!/bin/bash
#
# description:  ecm start cmd
# @author:      peacewong
# @created:     01.16.2021
#
# Modified for Linkis 1.0.0

# get log directory
cd `dirname $0`
cd ..
INSTALL_HOME=`pwd`

# set DSS_HOME
if [ "$DSS_HOME" = "" ]; then
  export DSS_HOME=$INSTALL_HOME
fi

# set DSS_CONF_DIR
if [ "$DSS_CONF_DIR" = "" ]; then
  export DSS_CONF_DIR=$DSS_HOME/conf
fi
source "$DSS_CONF_DIR"/config.sh

SERVER_SUFFIX="dss-flow-execution-server"
## set log
if [ "$DSS_LOG_DIR" = "" ]; then
  export DSS_LOG_DIR="$DSS_HOME/logs"
fi
export SERVER_LOG_PATH=$DSS_LOG_DIR/dss-orchestrator/$SERVER_SUFFIX
if [ ! -w "$SERVER_LOG_PATH" ] ; then
  mkdir -p "$SERVER_LOG_PATH"
fi

if test -z "$SERVER_HEAP_SIZE"
then
  export SERVER_HEAP_SIZE="512M"
fi

if test -z "$SERVER_JAVA_OPTS"
then
  export SERVER_JAVA_OPTS="-DserviceName=$SERVER_SUFFIX -Xmx$SERVER_HEAP_SIZE -XX:+UseG1GC -Xloggc:$SERVER_LOG_PATH/linkis.log"
fi

export SERVER_CLASS=com.webank.wedatasphere.dss.flow.execution.entrance.DSSFowExecutionServerApplication

## conf dir
export SERVER_CONF_PATH=$DSS_CONF_DIR:$DSS_CONF_DIR/$SERVER_SUFFIX

## commons lib
export DSS_COMMONS_LIB="$DSS_HOME/lib/dss-commons"


if [ ! -r "$DSS_COMMONS_LIB" ] ; then
    echo "dss commons lib not exists $DSS_COMMONS_LIB"
    exit 1
fi

## server lib
export SERVER_LIB=$DSS_HOME/lib/dss-orchestrator/$SERVER_SUFFIX


if [ ! -r "$SERVER_LIB" ] ; then
    echo "server lib not exists $SERVER_LIB"
    exit 1
fi

export SERVER_PID=$DSS_HOME/pid/${SERVER_SUFFIX}.pid
## set class path
export SERVER_CLASS_PATH=$SERVER_CONF_PATH:$DSS_COMMONS_LIB/*:$SERVER_LIB/*

nohup java $SERVER_JAVA_OPTS -cp $SERVER_CLASS_PATH $SERVER_CLASS 2>&1 > $SERVER_LOG_PATH/linkis.out &
pid=$!

sleep 2
if [[ -z "${pid}" ]]; then
    echo "server $SERVER_SUFFIX start failed!"
    exit 1
else
    echo "server $SERVER_SUFFIX start succeeded!"
    echo $pid > $SERVER_PID
    sleep 1
fi
exit 1
